name: form_bloc_web
description: Easy Form State Management using BLoC pattern. Separate the Form State and Business Logic from the User Interface.
version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # form_bloc:
  #   path: ../packages/form_bloc
  # flutter_form_bloc:
  #   path: ../packages/flutter_form_bloc
  flutter_form_bloc:
    git:
      url: https://github.com/WahdanZ/form_bloc
      ref: ns-mirgrate
      path: packages/flutter_form_bloc
  flutter_gradients: ^1.0.0+3
  flutter_syntax_view: ^3.2.2
  flash: ^1.5.0
  url_launcher: ^6.0.2
  flutter_markdown: ^0.6.0
  simple_animations: ^1.3.9
  auto_size_text: ^2.1.0
  flutter_fadein: ^1.1.1
  liquid_progress_indicator: ^0.3.2
  rxdart: ^0.26.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
  - family: JosefinSans
    fonts:
    - asset: assets/fonts/JosefinSans-Regular.ttf
    - asset: assets/fonts/JosefinSans-Bold.ttf
      weight: 700
  assets:
    - lib/examples/